name: Run Python script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes

env:
  DATASET_NAME: youtube_comments_data
  DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID: resounding-hope-414923
  DESTINATION__BIGQUERY__CREDENTIALS__LOCATION: US
  DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL: terraform-service-account@resounding-hope-414923.iam.gserviceaccount.com
  DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY: ${{ secrets.DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dlt[bigquery] toml pytz google-api-python-client google-auth-httplib2 google-auth-oauthlib

    - name: Run script
      run: | 
        export API_KEY=${{ secrets.API_KEY }}
        python dlt_pipeline.py